### ISSUE TITLE
allow a link to JavaScript string on tatowiki

### ISSUE THREAD

**Issue by alanfgh** [allan-simon/tatoebacpp#11]
Currently, it's impossible to put up a link to a JavaScript string on the Tatoeba wiki. This makes it impossible to put up links to bookmarklets that users can drag and drop to their bookmark menus. Bookmarklet strings can be found on the list of bookmarklets on the wiki.

**Comment by alanfgh** [comment]
sysko says he plans to put up a fix for this tomorrow (2014-01-19).

**Comment by allan-simon** [comment]
I've put the ticket here https://github.com/allan-simon/tatowiki/issues/78 as its related to tatowiki
