### ISSUE TITLE
Wiki main page sidebar should say "Deutsch", not "Deutsh"

### ISSUE THREAD

**Issue by alanfgh** [allan-simon/tatoebacpp#12]
[duplicate of Assembla ticket #382] On the wiki main page, in the right sidebar, under "Article available in:", the first item is "Deutsh". It should be "Deutsch".

**Comment by alanfgh** [comment]
This would be a good bug for a noob like me to fix.

**Comment by allan-simon** [comment]
fixed, it was actually a conf file that had not been updated (the repository already had the correction for a long time)

**Comment by alanfgh** [comment]
Verified.
